### PR TITLE
Add a File ID mapping file, for per-file dicts without modifying the checked file

### PR DESCRIPTION
**Pull request by cassella**
The description and some design notes are in the "Introduce fileid mapping file" commit header.

### CODE REVIEW

**Comment by myint** [comment]
I'm seeing the following.

```
$ ./.tox/py34/bin/scspell --relative-to=. README.rst
Traceback (most recent call last):
  File "./.tox/py34/bin/scspell", line 149, in <module>
    sys.exit(main())
  File "./.tox/py34/bin/scspell", line 144, in main
    args.c_escapes)
  File "/private/tmp/scspell/.tox/py34/lib/python3.4/site-packages/scspell/__init__.py", line 687, in spell_check
    with CorporaFile(dict_file, base_dicts, relative_to) as dicts:
  File "/private/tmp/scspell/.tox/py34/lib/python3.4/site-packages/scspell/_corpus.py", line 272, in __init__
    for k,v in self._fileid_mapping.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by cassella** [comment]
Looks like a python version thing.  It works for me with python 2.7,
but I get the same error with python 3.4.  I'll see what I can figure
out.

**Comment by cassella** [comment]
That was the only iteritems() I'd used, so that may do it.  I'll try testing some more things with python3.

BTW, README.rst contains the scspell-id: token, so the add menu will offer `(f)ile-specific`, rather than `(N)ew file specific`.

**Comment by cassella** [comment]
Nope, I found another python3 issue.

**Comment by cassella** [comment]
First awful workaround failed only on python 3.2.  Sigh.
This is slightly less awful.

I also fixed a small bug that was exposed when the above issue left the fileid mapping file present but empty.

**Comment by cassella** [comment]
Until writing a cram.test for this, I'd never tried invoking --rename-file from anywhere but the --relative-to directory itself.

It didn't work.  Fixed.

**Comment by cassella** [comment]
Hi.  Do you have any questions, concerns, complaints, bugs, just don't like the idea in the first place?

**Comment by myint** [comment]
I haven't had a chance to look at this deeply. How does this compare to #6?

**Comment by cassella** [comment]
No worries.

#6 is the same as this -- exactly the same commits -- except it has two additional commits on the end.
The last two commits add tests of the new features to test.cram.

I wasn't sure if that was the right way to add those tests (checking in test files and dictionaries in tests/, and having test.cram copy them to the temp test dir to operate on), so I left this PR open as well so it could be merged by itself instead if that was the wrong way to go about testing.

**Comment by myint** [comment]
I'll close this one for now and consider the other one to avoid confusion.

**Pull request closed without merging**
